#!/bin/sh -e

BACKJUMPS=-1

rm -rf dist-newstyle
rm -f cabal.project.local
cabal new-build --max-backjumps=$BACKJUMPS --reorder-goals --enable-tests $*
if echo $OS | grep -i windows; then
  `find dist-newstyle/build -name test.exe -a -type f`
else
  `find dist-newstyle/build -name test -a -type f`
fi
