#!/bin/sh -e

# Test the package across a number of configurations we expect to work.
# This relies on having with-ghc-XXX scripts available for each supported GHC v$

# The script doesn't currently use sandboxes for various reasons (lengthier builds
# and not supported by all versions of cabal) so it may not be completely reliable.
# The constraints specified have been observed to make it build in practice once
# but are not necessarily sufficient.
# TODO would probably be sensible to use 'cabal freeze' files instead where possible.

rm -rf .cabal-sandbox

# cover each GHC

test/with-ghc-7.0 test/check-package -f-warp-tests --constraint 'entropy<0.2.2.4'

test/with-ghc-7.4 test/check-package

test/with-ghc-7.6 test/check-package

test/with-ghc-7.8 test/check-package

test/with-ghc-7.10 test/check-package

# cover the min/max bounds for each package in turn (TODO: add this for each one)

# only have GHC 7.0.4 easily available to test with, so test
# base 4.3.1.0 instead of 4.3.0.0
test/with-ghc-7.0 test/check-package --constraint='base==4.3.1.0' -f-warp-tests
# don't have GHC 7.10 easily available to test with yet
test/with-ghc-7.8 test/check-package --constraint='base>=4.7'

test/with-ghc-7.0 test/check-package --constraint='parsec==2.0' --constraint 'network<2.3' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='parsec>=2.1'

test/with-ghc-7.0 test/check-package --constraint='array==0.3.0.2' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.8 test/check-package --constraint='array>=0.5'

test/with-ghc-7.0 test/check-package --constraint='old-time==1.0.0.0' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='old-time>=1.1'

test/with-ghc-7.0 test/check-package --constraint='bytestring==0.9.1.5' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='bytestring>=0.10'

test/with-ghc-7.6 test/check-package --constraint='httpd-shed==0.4' --constraint 'network<2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='httpd-shed>=0.4'

test/with-ghc-7.6 test/check-package --constraint='HUnit==1.2.0.1'
test/with-ghc-7.6 test/check-package --constraint='HUnit>=1.3'

test/with-ghc-7.0 test/check-package --constraint='test-framework==0.2.0' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='test-framework>=0.8'

test/with-ghc-7.0 test/check-package --constraint='test-framework-hunit==0.3.0' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='test-framework-hunit>=0.3'


# cover all major versions of network given it's quite central to HTTP
test/with-ghc-7.0 test/check-package --constraint='network==2.2.1.8' --constraint 'entropy<0.2.2.4' -f-warp-tests

test/with-ghc-7.6 test/check-package --constraint 'network>=2.3&&<2.4'
test/with-ghc-7.6 test/check-package --constraint 'network>=2.4&&<2.5'

# need to choose an http-shed with upper bounds, earlier versions won't build with network>=2.5
test/with-ghc-7.6 test/check-package --constraint 'network>=2.5&&<2.6' --constraint 'httpd-shed>=0.4.0.1'
test/with-ghc-7.6 test/check-package --constraint 'network>=2.6' --constraint 'httpd-shed>=0.4.0.1'

test/with-ghc-7.0 test/check-package --constraint='mtl==1.1.1.0' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='mtl>=2.2'

test/with-ghc-7.0 test/check-package --constraint='split==0.1.3' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='split>=0.2'

test/with-ghc-7.0 test/check-package --constraint='pureMD5==0.2.4' --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package --constraint='pureMD5>=2.1'

test/with-ghc-7.6 test/check-package --constraint='deepseq==1.3.0.0' --constraint='time<1.5'
# deepseq 1.4 not on hackage yet
test/with-ghc-7.6 test/check-package --constraint='deepseq>=1.3'

test/with-ghc-7.4 test/check-package --constraint='case-insensitive==0.4.0.1'
test/with-ghc-7.6 test/check-package --constraint='case-insensitive>=1.2'

test/with-ghc-7.4 test/check-package --constraint='http-types==0.8.0'
test/with-ghc-7.6 test/check-package --constraint='http-types>=0.8'

test/with-ghc-7.6 test/check-package --constraint='warp==2.1.0' --constraint='conduit<1.1'
test/with-ghc-7.6 test/check-package --constraint='warp>=3.0'

test/with-ghc-7.6 test/check-package --constraint='wai==2.1.0' --constraint='conduit<1.1'
# covering different versions with ifdefs
test/with-ghc-7.6 test/check-package --constraint='wai>=2.1&&<3.0'
test/with-ghc-7.6 test/check-package --constraint='wai==3.0.0'
test/with-ghc-7.6 test/check-package --constraint='wai>=3.0.1'

test/with-ghc-7.6 test/check-package --constraint='conduit==1.0.8' -fconduit10
test/with-ghc-7.6 test/check-package --constraint='conduit>=1.0' -fconduit10
test/with-ghc-7.6 test/check-package --constraint='conduit>=1.1'

test/with-ghc-7.6 test/check-package --constraint='conduit-extra==1.1'
test/with-ghc-7.6 test/check-package --constraint='conduit-extra>=1.1'


# cover each flag

test/with-ghc-7.0 test/check-package -fmtl1 --constraint 'entropy<0.2.2.4' -f-warp-tests
test/with-ghc-7.6 test/check-package -f-mtl1

# test/with-ghc-7.6 test/check-package -fwarn-as-error
test/with-ghc-7.6 test/check-package -f-warn-as-error

test/with-ghc-7.6 test/check-package -fnetwork23
test/with-ghc-7.6 test/check-package -f-network23

test/with-ghc-7.6 test/check-package -fconduit10
test/with-ghc-7.6 test/check-package -f-conduit10

test/with-ghc-7.6 test/check-package -fwarp-tests
test/with-ghc-7.6 test/check-package -f-warp-tests
